"""initial_tables

Revision ID: b542ac2a2c0f
Revises: 
Create Date: 2026-03-14 12:53:15.452902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b542ac2a2c0f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')
    op.create_table('textlites',
    sa.Column('id', sa.Text(), server_default=sa.text('uuid_generate_v4()::text'), nullable=False),
    sa.Column('json_content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('public_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('max_views', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index('idx_textlite_created_at', 'textlites', ['created_at'], unique=False)
    op.create_index('idx_textlite_expires_at', 'textlites', ['expires_at'], unique=False)
    op.create_index('idx_textlite_public_id', 'textlites', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_textlite_public_id', table_name='textlites')
    op.drop_index('idx_textlite_expires_at', table_name='textlites')
    op.drop_index('idx_textlite_created_at', table_name='textlites')
    op.drop_table('textlites')
    # ### end Alembic commands ###
